version: '3'
services:

  mysql:
   container_name: study.docker-test.mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: study
    MYSQL_ROOT_HOST: '%'
    MYSQL_ROOT_PASSWORD: password
   ports:
   - "3306:3306"
   restart: always

  nginx:
    container_name: study.docker-test.nginx
    image: nginx:1.15
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d

  app:
    container_name: study.docker-test.springboot
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
      - nginx
